### ISSUE TITLE
error on test with windows 10 - checkpoints.

### ISSUE THREAD

**Issue by catafest** [XingangPan/DragGAN#74]
I try to run it on windows 10 with this Python version 
`Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32`
The error is : 
`python visualizer_drag_gradio.py
Traceback (most recent call last):
  File "C:\PythonProjects\AI\DragGAN\visualizer_drag_gradio.py", line 151, in <module>
    for f in os.listdir(cache_dir)
             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: './checkpoints'
`
Any idea how to fix it?

**Comment by icecreamzhao** [comment]
on windows:
./scripts/download_model.bat

if you notice the error message, you will find "The system cannot find the path specified: './checkpoints'", because you don't download the checkpoints

**Comment by catafest** [comment]
I got this error:

````
download_model.bat
Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out."
At line:1 char:1
+ (New-Object System.Net.WebClient).DownloadFile('https://storage.googl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
The system cannot find the file specified.
````

**Comment by icecreamzhao** [comment]
emm, you can edit this file, check all download links and copy that to browser, when download complete, copy all download file to “checkpoints” folder.

**Comment by catafest** [comment]
works, I think I stop running script , or something else .

**Comment by swisspb** [comment]
Could you please unsubscribe me ???


Thanks Guys

Olivier Cohen
Founder, C.O.O.


Place des Florentins 1
1204 Geneva
Switzerland
(Tel) +41 22 707 73 76
(Fax) +41 22 707 73 77
(Mob)+41 79 951 21 38
***@***.***


Le 28 juin 2023 à 02:45, nexzhao ***@***.***> a écrit :




﻿

emm, you can edit this file, check all download links and copy that to browser, when download complete, copy all download file to “checkpoints” folder.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you are subscribed to this thread.Message
 ID: ***@***.***>
